country = ['Italia', 'Austira', 'China', 'Japan', 'Germany']
print(country)
print(sorted(country))
print(sorted(country, reverse=True))
print(country)
country.reverse()
print(country)
country.reverse()
print(country)
country.sort()
print(country)
country.sort(reverse=True)
print(country)